services:
  - type: web
    name: dexter-ai-backend
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true 